- name: ansible
  src: https://github.com/geerlingguy/ansible-role-ansible
  version: 1.3.0

- name: apache
  src: git+https://github.com/geerlingguy/ansible-role-apache.git
  version: 2.1.1

- name: nodejs
  src: https://github.com/geerlingguy/ansible-role-nodejs
  version: 5.1.1

- name: caddy
  src: https://github.com/caddy-ansible/caddy-ansible
  version: v2.1.0

- name: cadvisor
  src: https://github.com/ome/ansible-role-cadvisor/
  version: 0.3.1

- name: docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.9.0

- name: flatkey.firewalld
  src: https://github.com/FlatKey/ansible-firewalld-role
  version: v1.3.0

- name: grafana
  src: https://github.com/cloudalchemy/ansible-grafana
  version: 0.14.2

- name: prometheus
  src: https://github.com/cloudalchemy/ansible-prometheus
  version: 2.10.0

- name: prometheus-node-exporter
  src: https://github.com/UnderGreen/ansible-prometheus-node-exporter.git
  version: v1.4.0

- name: UnderGreen.prometheus-exporters-common
  src: https://github.com/UnderGreen/ansible-prometheus-exporters-common.git
  version: v1.2.0

- name: sshd
  src: git+https://github.com/willshersystems/ansible-sshd.git
  version: v0.5.1

- name: sudo
  src:  https://github.com/weareinteractive/ansible-sudo
  version: 1.7.1

- name: ssh_config
  src: https://github.com/gaqzi/ansible-ssh-config
  path: library
