---
- name: Start prometheus-cadvisor container
  docker_container:
    image: '{{ prom_cadvisor_image }}:{{ prom_cadvisor_tag }}'
    name: '{{ prom_cadvisor_name }}'
    ports: '{{ prom_cadvisor_internal_port }}:{{ prom_cadvisor_external_port }}'
    state: started
    privileged: yes
    devices:
      - "/dev/zfs"
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/zfs:/dev/zfs:ro
      - /cgroup:/cgroup:ro

- name: Create file_sd_config fragment for prometheus
  template:
    src: cadvisor_file_sd_config.yml.j2
    dest: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-cadvisor_file_sd_config.yml"

- name: Retain a copy of the file_sd_config fragment for stats host
  fetch:
    src: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-cadvisor_file_sd_config.yml"
    dest: "{{ prometheus_exporters_common_local_sd_conf_dir }}/{{ inventory_hostname }}-cadvisor_file_sd_config.yml"
    flat: yes


