# Set this to a path to use ephemeral storage
openstack_ephemeral_docker_disk: ""

openstack_ephemeral_docker_align: 'optimal'
openstack_ephemeral_docker_partition: 1
openstack_ephemeral_docker_start: '2048s'
openstack_ephemeral_docker_end: '100%'
openstack_ephemeral_part_type: 'primary'

# Set this to a ZFS pool to use ZFS storage
docker_zfs_pool: ""
