callysto_hub_landing_page_repo: "https://github.com/callysto/hub-landing-page"
callysto_landing_branch: "template-callysto"
callysto_html_hostname: "{{ inventory_hostname }}"
callysto_html_domain: "callysto.ca"
callysto_html_support_email: "support@callysto.ca"
callysto_html_url: "http://{{ inventory_hostname }}"

callysto_ssl_cert_dir:

callysto_html_dir:
  src: /opt/hub-landing-page
  dest: /var/www/html/site

callysto_html_logout_message: "You have been logged out of your Jupyter Session"

callysto_html_terms: |
  By using this service you are indicating that you agree with the Callysto
  <a href="https://www.callysto.ca/wp-content/uploads/2021/03/CallystoTermsofService-July2019.pdf">Terms
  of Service</a> and <a href="https://www.callysto.ca/wp-content/uploads/2021/03/CallystoPrivacyNotice-July2019.pdf">Privacy
  Notice</a>.

  Questions? <a href="mailto:support@callysto.ca">Contact us</a>
