---
# Overlay2
- name: Partition OpenStack Ephemeral Storage
  parted:
    device: '{{ openstack_ephemeral_docker_disk }}'
    number: '{{ openstack_ephemeral_docker_partition }}'
    align: '{{ openstack_ephemeral_docker_align }}'
    part_start: '{{ openstack_ephemeral_docker_start }}'
    part_end: '{{ openstack_ephemeral_docker_end }}'
    part_type: '{{ openstack_ephemeral_part_type }}'
    state: present
  when: openstack_ephemeral_docker_disk != ""
  register: restartdocker

- name: Create an XFS filesystem on the storage
  filesystem:
    fstype: xfs
    dev: '{{ openstack_ephemeral_docker_disk }}{{ openstack_ephemeral_docker_partition }}'
  when: openstack_ephemeral_docker_disk != ""
  register: restartdocker

- name: Mount the ephemeral for docker
  mount:
    src: '{{ openstack_ephemeral_docker_disk}}{{ openstack_ephemeral_docker_partition }}'
    path: '/var/lib/docker'
    fstype: 'xfs'
    state: 'mounted'
  when: openstack_ephemeral_docker_disk != ""
  register: restartdocker

# ZFS
- name: Ensure /etc/systemd/system/docker.service.d exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: docker_zfs_pool != ""

- name: Ensure /etc/systemd/system/docker.service.d/docker.conf exists
  template:
    src: docker-zfs.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
  when: docker_zfs_pool != ""
  register: dockerconf

- name: Ensure /var/lib/docker does not exist
  file:
    path: /var/lib/docker
    state: absent
  register: restartdocker

- name: systemctl reload
  systemd: daemon_reload=yes
  when: dockerconf.changed

- name: restart docker
  service: name=docker state=restarted
  when: restartdocker.changed or dockerconf.changed

- name: Flush Handlers
  meta: flush_handlers
