---
- name: Create file_sd_config fragment for prometheus
  template:
    src: file_sd_config.yml.j2
    dest: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"

- name: Retain a copy of the file_sd_config fragment for stats host
  fetch:
    src: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"
    dest: "{{ prometheus_exporters_common_local_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"
    flat: yes
